# Generated by Django 4.1.4 on 2023-03-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_s', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_s', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='places',
        ),
    ]
